### ISSUE TITLE
方案说明

### ISSUE THREAD

**Issue by luuuyi** [sankin97/Underwater_detection#1]
作者你好，我看到你方案说明里面GC和mixup都有效，但是在你的最终模型里面B模型不包含mixup，A和B都不包含GC模块，这个能说明下是什么原因么

**Comment by sankin97** [comment]
关于mixup我们在A榜上面实验效果提升很高，但使用mixup的模型在b榜的效果是减分的，可能数据分布的问题。
关于GC模块，我们在A/B榜均有使用，具体可见[single_level.py](https://github.com/sankin97/Underwater_detection/blob/master/mmdet/models/roi_extractors/single_level.py),我们做了改进，则在configs中只需置gc_context=True即可
